import type { Metadata } from "next";
import { Ubuntu, Ubuntu_Mono } from "next/font/google";
import { DataProvider } from "./Contexts/DataContext";

import '@mantine/core/styles.css';
import "./globals.css";

import { MantineProvider, mantineHtmlProps } from '@mantine/core';


const ubuntu = Ubuntu({
    weight: "400",
    subsets: ["latin"]
})

const ubuntuMono = Ubuntu_Mono({
    weight: "400",
    subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "HokkienMee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <body
        className={`${ubuntuMono.className} antialiased flex flex-col justify-center items-center h-screen`}
      >
        <MantineProvider>
            <DataProvider>{children}</DataProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
